# Основная документация: https://github.com/dorny/paths-filter (см. всё к полю `filters`)

# Пути прописываются в виде picomatch-паттернов:
#   https://github.com/micromatch/picomatch#basic-globbing

# Можно использовать все фишки YAML-я:
#   https://ru.wikipedia.org/wiki/YAML#%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81

# Имена последних объектов (xi-frodo, lintable) лучше не менять

configs: &configs  # изменения тут обязательно запускают все пайплайны
  - ".github/workflows/*"
  - "package.json"
  - "package-lock.json"
  - "**/package.json"
  - "**/package-lock.json"

app_common: &app_common  # тригерят оба билда (и депой в main-ветке)
  - *configs
  - "packages/**"
  - "Dockerfile"
  - "turbo.json"

xi-frodo:  # запускает билд (и депой в main-ветке) для xi.frodo
  - *app_common
  - "apps/xi.frodo/**"

lintable:  # запускает прогон линтера
  - *configs
  - "**.[jt]s"
  - "**.[jt]sx"
  - "**.md"
