name: Common Preparation Steps

on:
  workflow_call:
    outputs:
      xi-frodo:
        description: Will be 'true' xi.frodo's files have changed
        value: ${{ jobs.analyze_files.outputs.xi-frodo }}

jobs:
  analyze_files:
    runs-on: ubuntu-latest

    env:
      filename: .github/workflows/generated_filters.yml

    outputs:
      lintable: ${{ steps.path_filter.outputs.lintable }}
      xi-frodo: ${{ steps.path_filter.outputs.xi-frodo }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: path_filter
        with:
          filters: .github/files.yml

  lint_and_format:
    needs: analyze_files
    if: needs.analyze_files.outputs.lintable == 'true'
    uses: xi-effect/xieffect-actions/.github/workflows/front-lint-and-format.yml@main
